[project]
name = "autoqa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Derylian Khalfani", email = "mderylkhalfani@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
autoqa = "autoqa:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
